services:
    sonata.admin.stuff:
        class: Shukay\AdminBundle\Admin\StuffAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Stuff", label: "Stuff" }
        arguments:
            - ~
            - Shukay\StuffBundle\Entity\Stuff
            - ~
        calls:
            - [ setTranslationDomain, [ShukayAdminBundle]]

    sonata.admin.location:
            class: Shukay\AdminBundle\Admin\LocationAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Map", label: "Location" }
            arguments:
                - ~
                - Shukay\MapBundle\Entity\Location
                - ~
            calls:
                - [ setTranslationDomain, [ShukayAdminBundle]]