services:
    sonata.admin.stuff:
        class: Shukay\AdminBundle\Admin\StuffAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Stuff", label: "Stuff" }
        arguments:
            - ~
            - Shukay\StuffBundle\Entity\Stuff
            - ~
        calls:
            - [ setTranslationDomain, [ShukayAdminBundle]]

    sonata.admin.location:
            class: Shukay\AdminBundle\Admin\LocationAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Map", label: "Location" }
            arguments:
                - ~
                - Shukay\MapBundle\Entity\Location
                - ~
            calls:
                - [ setTranslationDomain, [ShukayAdminBundle]]

    sonata.admin.profile.information:
                class: Shukay\AdminBundle\Admin\ProfileInformationAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: "User", label: "ProfileInformation" }
                arguments:
                    - ~
                    - Shukay\UserBundle\Entity\ProfileInformation
                    - ~
                calls:
                    - [ setTranslationDomain, [ShukayUserBundle]]

    admin.menu:
            class: Shukay\AdminBundle\Admin\MenuAdmin
            tags:
            - { name:  sonata.admin, manager_type: orm, group: Меню, label: Меню}
            arguments: [null, Shukay\MenuBundle\Entity\Menu, SonataAdminBundle:CRUD]

    admin.menu_type:
            class: Shukay\AdminBundle\Admin\MenuTypeAdmin
            tags:
            - { name:  sonata.admin, manager_type: orm, group: Меню Тип, label: Меню Тип}
            arguments: [null, Shukay\MenuBundle\Entity\MenuType, SonataAdminBundle:CRUD]