imports:
    - { resource: parameters.yml }
    - { resource: gmap.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: sonata.yml }
    - { resource: sonata_core.yml }
    - { resource: twig.yml }
    - { resource: @ShukayAdminBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
                    default:
                        mappings:
                            ShukayUserBundle: ~
                            ShukayStuffBundle: ~
                            ShukayMenuBundle: ~
                            ShukayMapBundle: ~
                            ShukayOAuthBundle: ~
                            FOSUserBundle: ~



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver:        orm # can be orm or odm
    firewall_name:    main
    user_class:       Shukay\UserBundle\Entity\User
    group:
        group_class:  Shukay\UserBundle\Entity\Group

fos_oauth_server:
    db_driver:           orm
    client_class:        Shukay\OAuthBundle\Entity\Client
    access_token_class:  Shukay\OAuthBundle\Entity\AccessToken
    refresh_token_class: Shukay\OAuthBundle\Entity\RefreshToken
    auth_code_class:     Shukay\OAuthBundle\Entity\AuthCode


knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

oneup_uploader:
    mappings:
        stuff:
            frontend: custom
            custom_frontend:
                class: Shukay\DropzoneBundle\Controller\DropzoneController
                name: MyFancyCustomUploader