shukay_menu:
    resource: "@ShukayMenuBundle/Resources/config/routing.yml"
    prefix:   /

shukay_o_auth:
    resource: "@ShukayOAuthBundle/Resources/config/routing.yml"
    prefix:   /

shukay_map:
    resource: "@ShukayMapBundle/Resources/config/routing.yml"
    prefix:   /

shukay_stuff:
    resource: "@ShukayStuffBundle/Resources/config/routing.yml"
    prefix:   /

shukay_admin:
    resource: "@ShukayAdminBundle/Resources/config/routing.yml"
    prefix:   /

shukay_user:
    resource: "@ShukayUserBundle/Resources/config/routing.yml"
    prefix:   /user/

shukay_main:
    resource: "@ShukayMainBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

