security:
    acl:
        connection: default
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: shukay.security.authentication_handler
                failure_handler: shukay.security.authentication_handler
            logout:       true
            anonymous:    true
        oauth_authorize:
                    pattern: ^/oauth/v2/auth
                    form_login:
                        provider: fos_userbundle
                        check_path: /oauth/v2/auth_login_check
                        login_path: /oauth/v2/auth_login
                    anonymous: true
        oauth_token:
                    pattern: ^/oauth/v2/token
                    security: false

        api:
                    pattern:    ^/api
                    fos_oauth:  true
                    stateless:  true
                    anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN