twig:
    form:
        resources:
                - "ShukayDropzoneBundle:Dropzone:dropzone.type.html.twig"
                - "ShukayMapBundle:Location:location.type.html.twig"
    globals:
        gapi:  "@gapi"
        google_map:    "%google_map%"


