parameters:
#    shukay_menu.example.class: Shukay\MenuBundle\Example

services:
  menu:
        class: Shukay\MenuBundle\Service\MenuService
        arguments: [@service_container]

  shukay.menu_builder:
        class: Shukay\MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@service_container"]

  shukay.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: shukay.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

  twitter_bootstrap.menu_renderer:
          class: Shukay\MenuBundle\Menu\TwitterBootstrapRenderer
          arguments:
              - @twig
              - 'ShukayMenuBundle:Bootstrap:knp.bootstrap.renderer.twig'
              - @knp_menu.matcher
          tags:
              - { name: knp_menu.renderer, alias: bootstrap }
