user_view:
    pattern:  /user/{username}
    defaults: { _controller: ShukayUserBundle:Profile:index, username: null }

profile:
    pattern:  /profile
    defaults: { _controller: ShukayUserBundle:Profile:index, username: null }

registration:
    pattern:  /registration
    defaults: { _controller: ShukayUserBundle:Register:register }

registration_confirm:
    pattern:  /registration/confirm/{token}
    defaults: { _controller: ShukayUserBundle:Register:confirm }

registration_confirmed:
    pattern:  /registration/confirmed
    defaults: { _controller: ShukayUserBundle:Register:confirmed }

registration_check_email:
    pattern:  /registration/check-email
    defaults: { _controller: ShukayUserBundle:Register:checkEmail }

change_profile:
    pattern:  /profile/change-profile
    defaults: { _controller: ShukayUserBundle:Profile:changeProfile }

update_profile:
    pattern:  /profile/update-profile/{id}
    defaults: { _controller: ShukayUserBundle:Profile:updateProfile }
    methods:  [PUT]

change_password:
    pattern:  /profile/change-password
    defaults: { _controller: ShukayUserBundle:ChangePassword:changePassword }

change_email:
    pattern:  /profile/change-email
    defaults: { _controller: ShukayUserBundle:Profile:changeEmail }

login_form:
    pattern:  /get-form
    defaults: { _controller: FOSUserBundle:Security:login }


