shukay_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ShukayUserBundle:Default:index }

login_form:
    pattern:  /get-form
    defaults: { _controller: FOSUserBundle:Security:login }
