services:
    shukay.security.authentication_handler:
            class: Shukay\UserBundle\Handler\AuthenticationHandler
            public: false
            arguments:
                - @router
                - @session