parameters:
#    shukay_user.example.class: Shukay\UserBundle\Example

services:
#    shukay_user.example:
#        class: %shukay_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
