<?php

namespace Shukay\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileInformationRepository extends EntityRepository
{
}
