parameters:
#    shukay_mail.example.class: Shukay\MailBundle\Example

services:
    user.mail_service:
          class: Shukay\MailBundle\Mailer\UserMailer
          arguments: [@mailer,@router,  @templating, from_email { confirmation: '%fos_user.registration.confirmation.from_email%' } ]


