parameters:
#    shukay_o_auth.example.class: Shukay\OAuthBundle\Example

services:
#    shukay_o_auth.example:
#        class: %shukay_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
