parameters:
#    shukay_map.example.class: Shukay\MapBundle\Example

services:
#    shukay_map.example:
#        class: %shukay_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
